# Generated by Django 4.0.2 on 2022-03-03 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password_salt', models.CharField(max_length=100)),
                ('email_salt', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('picture_location', models.CharField(max_length=50)),
                ('is_mentor', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=50)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField()),
                ('text', models.CharField(max_length=200)),
                ('reviewedID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='api.users')),
                ('reviewerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='MentorMentees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menteeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to='api.users')),
                ('mentorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=50)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventID', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('mentorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='EventMentees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
                ('menteeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('messageID', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('date_sent', models.DateTimeField()),
                ('chatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chat')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='userID1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='api.users'),
        ),
        migrations.AddField(
            model_name='chat',
            name='userID2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='api.users'),
        ),
    ]
